import { mockStudy } from "../mockData";
import { AssessmentStudyResponse, Event } from "../types";

export async function fetchStudy(
  studyId: string,
  _signal?: AbortSignal,
): Promise<AssessmentStudyResponse> {
  const latency = Math.random() * 800 + 200; // 200-1000ms random delay
  await new Promise((r) => setTimeout(r, latency));

  const studyOffset = studyId.includes("002")
    ? 10
    : studyId.includes("003")
    ? 20
    : 0;

  const clone: AssessmentStudyResponse = {
    metadata: {
      ...mockStudy.metadata,
      study_id: studyId || mockStudy.metadata.study_id,
    },
    signals: {
      hr: mockStudy.signals.hr
        ? {
            ...mockStudy.signals.hr,
            values: mockStudy.signals.hr.values.map((v) => v + studyOffset),
          }
        : undefined,
      spo2: mockStudy.signals.spo2
        ? {
            ...mockStudy.signals.spo2,
            values: mockStudy.signals.spo2.values.map((v) => v - studyOffset),
          }
        : undefined,
      resp: mockStudy.signals.resp
        ? {
            ...mockStudy.signals.resp,
            values: [...mockStudy.signals.resp.values],
          }
        : undefined,
      position: mockStudy.signals.position
        ? {
            ...mockStudy.signals.position,
            values: [...mockStudy.signals.position.values],
          }
        : undefined,
    },
    events: mockStudy.events.map((e: Event) => ({ ...e })),
  };
  return clone;
}

export async function fetchEvents(_studyId: string): Promise<Event[]> {
  // Simulate polling and events mutability
  await new Promise((r) => setTimeout(r, 250));
  return mockStudy.events.map((e: Event) => ({
    ...e,
    autogenerated: Math.random() > 0.3,
  }));
}
