export interface SignalSeries {
  timestamps?: number[];
  values: number[];
  start_time?: number;
  sample_rate?: number;
}

export interface Signals {
  hr?: SignalSeries;
  spo2?: SignalSeries;
  resp?: SignalSeries;
  position?: SignalSeries;
}

export interface Event {
  id: string;
  ts: number;
  label: string;
  autogenerated?: boolean;
}

export interface AssessmentStudyResponse {
  metadata: {
    study_id: string;
    study_start: number;
    study_end: number;
  };
  signals: Signals;
  events: Event[];
}

export interface GlobalState {
  studyId: string;
  loading: boolean;
  error?: string;
  signals: Signals;
  visibleSignals: Signals;
  events: Event[];
  yMin?: number;
  yMax?: number;
  chartWidth: number;
  chartHeight: number;
  autoScale: boolean;
  lastFetchedAt?: number;
  pollMs: number;
  currentStartSec: number;
  currentEndSec: number;
}
