export interface SignalSeries {
  timestamps?: number[];
  values: number[];
  start_time?: number;
  sample_rate?: number;
}

export interface Signals {
  hr?: SignalSeries;
  spo2?: SignalSeries;
  resp?: SignalSeries;
  position?: SignalSeries;
}

export interface Event {
  id: string;
  ts: number;
  label: string;
  autogenerated?: boolean;
}

export interface AssessmentStudyResponse {
  metadata: {
    study_id: string;
    study_start: number;
    study_end: number;
  };
  signals: Signals;
  events: Event[];
}

export type SignalKey = "hr" | "spo2" | "resp" | "position";

export interface StudyState {
  studyId: string;
  loading: boolean;
  error?: string;
  lastFetchedAt?: number;
  pollMs: number;
}

export interface WindowRange {
  startSec: number;
  endSec: number;
}

export interface ChartConfig {
  width: number;
  height: number;
}
